### ISSUE TITLE
Couple documentation issues

### ISSUE THREAD

**Issue by Silarn** [splashlab/magento-2-cors-requests#1]
Most importantly, you reference the composer package as splashlab/magento-2-cors-requests - however the actual package name as defined in your composer.json file is splashlab/cors-requests.

Additionally, it seems you still have some copied text present under your references section that doesn't match the actual module. :)

**Comment by thaddeusmt** [comment]
Hey sorry, I just fixed the composer.json file.

Can you be more specific about the copied references I have which don't match the module?

**Comment by thaddeusmt** [comment]
Derp, I see it. Fixed as well. Thanks!!
