### ISSUE TITLE
Add AMP headers

### ISSUE THREAD

**Issue by albertobraschi** [splashlab/magento-2-cors-requests#10]
Thank you for your plugin!
Awesome

SplashLab\CorsRequests\Plugin\CorsHeadersPlugin

    public function beforeDispatch(
        FrontControllerInterface $subject,
        RequestInterface $request
    ) {
        if ($originUrl = $this->getOriginUrl()) {
            $this->response->setHeader('Access-Control-Allow-Origin', rtrim($originUrl,"/"), true);
            $this->response->setHeader('AMP-Access-Control-Allow-Source-Origin', rtrim($originUrl,"/"), true);
            if ($this->getAllowCredentials()) {
                $this->response->setHeader('Access-Control-Allow-Credentials', 'true', true);
            }
        }
    }

**Comment by thaddeusmt** [comment]
I have not tested this, so it's just on the master branch right now, but give commit #
cc5af63 a go and see if it works.

**Comment by thaddeusmt** [comment]
Hopefully the AMP update (now released in version `100.0.3`) worked for you - if not please open a new bug, thanks.
