### ISSUE TITLE
Problems getting Module to work

### ISSUE THREAD

**Issue by KristianJohansenVakwerk** [splashlab/magento-2-cors-requests#11]
Hey, 

First of all thanks for writing this module.

I have tried adding it to my Magento 2 installation but I don't see any CORS settings in the Store -> General -> Web, I've cloned your repo. Created the folder structure and uploaded the content of the clone into that. Then I ran the php bin/magento setup:upgrade and php bin/magento setup:static-content:deploy. It might be here the problem is I get what looks like errors. Can I do sudo to force it? 

Thanks in advance!

**Comment by thaddeusmt** [comment]
Sorry this has languished for so long - I am not actively developing Magento currently, so it'll take more time than I have to spin things up to try to help you debug this. The recommended install method is via Composer, there is more room for permission errors with the manual install. Without seeing the `setup:upgrade` output which you say has "what looks like errors", I'm afraid I don't have a good guess about what is going wrong. Hopefully you found a solution in the intervening months!

**Comment by thaddeusmt** [comment]
Since I am not working with Magento currently and have not been updating this extension, please check out [graycoreio/magento2-cors](https://github.com/graycoreio/magento2-cors) to enable CORS on your Magento 2 site.
