### ISSUE TITLE
New release with PHP 7.2 support

### ISSUE THREAD

**Issue by marcoboom** [splashlab/magento-2-cors-requests#12]
Hi, 

Are you planning a new release on packagist with your latest changes with PHP 7.2 support? We are using the package already on PHP 7.2 and everything works fine.

However we prefer to fetch the extension with composer on a release instead of dev-master.

**Comment by thaddeusmt** [comment]
I just tagged a new `100.0.3` release and published to Packagist. Go ahead and close this bug if that works for you, thanks.

**Comment by evs-xsarus** [comment]
Works for me, @marcoboom you can update the version in your project ;).

**Comment by thaddeusmt** [comment]
I did eventually update support to PHP 7.2 in [100.0.3](https://github.com/splashlab/magento-2-cors-requests/releases/tag/100.0.3), and now PHP 7.3 in new release [100.0.4](https://github.com/splashlab/magento-2-cors-requests/releases/tag/100.0.4).
