### ISSUE TITLE
Environment variables to override configuration settings don't work.

### ISSUE THREAD

**Issue by DmitriyArbuzov** [splashlab/magento-2-cors-requests#18]
CONFIG__STORES__<STORE>__WEB__<PARAMETER_PATH> is not working.

Please fix this by changing `corsRequests` to `cors_requests` in config.xml and other required files.
So CONFIG__STORES__<STORE>__WEB__CORS_REQUESTS__ORIGIN_URL must work.

**Comment by thaddeusmt** [comment]
You are saying that a parameter path like 'web/**corsRequests**/origin_url' is no longer working, and the paths need to be 'web/**cors_requests**/origin_url' now?

Huh, was there an update in Magento core that makes this change necessary?

**Comment by DmitriyArbuzov** [comment]
I'm not sure that `corsRequests` have ever worked for environment variables to override configuration. In my case pattern `corsRequests` does not work and `cors_requests` works fine. I believe the valid pattern is with dash delimiter like `cors_requests`.

**Comment by Horbarz** [comment]
Please how do I edit the composer.json file, it seems to be a bit confusing
