### ISSUE TITLE
CORS Origin Url doesn't accept '*' as described

### ISSUE THREAD

**Issue by Silarn** [splashlab/magento-2-cors-requests#2]
It appears the JavaScript validator on the admin system_config page is preventing the use of the '*' entry for the 'CORS Origin Url'. (Despite being mentioned as an option in the 'hint' message.)

"Please enter a valid URL. Protocol is required (http://, https:// or ftp://)."

**Comment by thaddeusmt** [comment]
Thanks, I just updated the configuration so it doesn't try to validate URLs, give it a try now.
