### ISSUE TITLE
Use with Magento 2.4.x and PHP 7.4

### ISSUE THREAD

**Issue by fleischanderl** [splashlab/magento-2-cors-requests#20]
Hi, thank you for the great plugin. 

I updated my Magento 2.3 to Magento 2.4 and testet your plugin with php7.4 (requirement for magento2.4) and it still works but i can not use composer update. your comooser.json require:"php": "~7.1.3||~7.2.0||~7.3.0||"

Could you test the plugin and update the requirements?

Kind Regards

**Comment by stephanie-ehrling** [comment]
Yes, it would be great if the php reqs are updated to php 7.4.

**Comment by thaddeusmt** [comment]
I bumped the PHP version to 7.4, thank you for the reminder.
