### ISSUE TITLE
[Feature] Enabling GraphQL CORS

### ISSUE THREAD

**Issue by matasnizamovas** [splashlab/magento-2-cors-requests#22]
Is it in the plans to enable this CORS configuration to work with GraphQL endpoints in addition to Rest?

**Comment by damienwebdev** [comment]
@matasnizamovas see https://github.com/splashlab/magento-2-cors-requests/issues/21

**Comment by thaddeusmt** [comment]
As @damienwebdev points out, I am not working with Magento currently and have little bandwidth to maintain or enhance this extension, so there is no plan to add GraphQL support at the moment. 

His Magento 2 CORS extension might be more useful, it appears to support GraphQL: [graycoreio/magento2-cors](https://github.com/graycoreio/magento2-cors)

Feel free to submit a pull request adding support for GraphQL endpoints, though, if you have forked this and built it yourself, I can merge it in. Thank you.
