### ISSUE TITLE
magento 2.4.4 compatibility

### ISSUE THREAD

**Issue by msankhla** [splashlab/magento-2-cors-requests#25]
Hello,
As i can see through the composer, this module is compatible for PHP version 7.4, is there any latest update for PHP 8.1. Please share if there is any. 
Thanks

Mudit Sankhla

**Comment by sebastian-ehrling** [comment]
see here my pull request
https://github.com/splashlab/magento-2-cors-requests/pull/26

**Comment by thaddeusmt** [comment]
I merged the pull request from @sebastian-ehrling to meet PHP 8.1 requirement. Hopefully that's all that is needed to work with Magento 2.4.4. Sorry I am not involved in Magento development currently so it is hard for me to test.
