### ISSUE TITLE
Module doesn't work properly

### ISSUE THREAD

**Issue by rizalio** [splashlab/magento-2-cors-requests#3]
Hi! Thanks for creating this great module, I've installed magento2 on my local server with MAMP, I trying to make an ionic based mobile apps that request the authentication to `/V1/integration/admin/token` endpoint, But I'm facing Issue that my HTTP POST requests not sent properly instead of OPTIONS request see below : 

![screen shot 2017-10-16 at 10 50 44 am](https://user-images.githubusercontent.com/22221916/31596796-61faabf8-b277-11e7-93a1-ec409b854bb6.png)

I don't think this is Angular Http fault, after searching on Google I found the article about CORS & I try to enabling CORS on my Magento installation with your package, but it seems doesn't have any change.

**Comment by thaddeusmt** [comment]
It's hard to tell what is going wrong from this report.

Did you configure the Magento extension correctly in the "General -> Web -> CORS Requests Configuration" area?

I'm not sure CORS requests will work properly on "localhost" anyway...
https://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin

**Comment by thaddeusmt** [comment]
I'm going to close this since it's so old - sorry I was not able to help. Please open a new bug if you are still experiencing issues. Thanks.
