### ISSUE TITLE
how to set CORS Origin Url value?

### ISSUE THREAD

**Issue by chenghuili** [splashlab/magento-2-cors-requests#4]
Hi,
I have configured CORS Origin Url to * or https://cdn.magentobiz.com, but both value was not working for me, it still show following errors:

(index):1 Access to Font at 'https://cdn.magentobiz.com/pub/static/frontend/magentobiz/default/zh_Hans_CN/fonts/Pe-icon-7-stroke.woff?d7yf1v' from origin 'https://www.magentobiz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.magentobiz.com' is therefore not allowed access.

Thank you

**Comment by chenghuili** [comment]
I used cloudfront , and I have tried many ways to search on google, but all of ways not working for me

**Comment by bruno-serfe** [comment]
Hi Guys I've same issue in a Magento 2.2.5 using cloudflare as CDN, do you know a way to fix that without using this plugin? I've tried modifying .htaccess and pub/static/.htaccess in order to add 

`Header set Access-Control-Allow-Origin "*"`

without success
The fonts are not allowed and are cancelled in requests, but html content display an error in the console but is loaded after all.. any help will be grateful I think at the end is the same issue that @chenghuili is experiencing.

Thanks!

**Comment by floorz** [comment]
@bruno-serfe 

## In your pub/.htaccess
Replace `[URL]`'s with specific urls you want to allow

```
<IfModule mod_headers.c>
    # CORS Whitelisting
    <FilesMatch ".(eot|ttf|ttc|otf|woff|woff2|html|js|iframe|font.css|css|ico|json)">
        SetEnvIf Origin "http(s)?://([URL]|[URL]|[URL])$" AccessControlAllowOrigin=$0
        Header set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
        Header set Access-Control-Allow-Headers "x-requested-with"
    </FilesMatch>
</IfModule>
```

## In your pub/static/.htaccess
Replace `[URL]`'s with specific urls you want to allow

```
<IfModule mod_headers.c>
    # CORS Whitelisting
    <FilesMatch ".(eot|ttf|ttc|otf|woff|woff2|html|js|iframe|font.css|css|ico|json)">
        SetEnvIf Origin "http(s)?://([URL]|[URL]|[URL])$" AccessControlAllowOrigin=$0
        Header set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
        Header set Access-Control-Allow-Headers "x-requested-with"
    </FilesMatch>
</IfModule>
```

**Comment by bruno-serfe** [comment]
Hi @floorz thanks for the quick reply, I've tried that but is still not working, I don't know what's the issue here.. I'll need to further research on this.

**Comment by thaddeusmt** [comment]
Going above and beyond @floorz! Providing Apache support on here even ;). 

Sorry I have not been answering issues well, I'm not working on Magento projects at the moment, and won't be for the foreseeable future - so thanks for helping pick up my slack.

@chenghuili For what it's worth, I did merge @floorz PR, I hope that helps fix the issue.

**Comment by bruno-serfe** [comment]
OK, I managed to make it work in pub/.htaccess but not in the same way with fonts in pub/static/.htaccess weird thing

**Comment by floorz** [comment]
@bruno-serfe Are you serving your site from the pub directory or one directory up?

**Comment by bruno-serfe** [comment]
Hi @floorz the CDN is pointing to "magento_root/pub/" directory, and CDN configuration is as follows https://mycdn.com/static/ and https://mycdn.com/media/

**Comment by bruno-serfe** [comment]
Hi @floorz in my case the solution was to add the code mentioned in comment https://github.com/splashlab/magento-2-cors-requests/issues/4#issuecomment-408214458
in the CDN vhost

**Comment by thaddeusmt** [comment]
Thank you @floorz for helping @bruno-serfe.

Sorry I was not able to help @chenghuili with the original bug, hopefully the `.htaccess` fix will work?

Could there be a way to fix this in the extension itself? Without new `.htaccess` directives? I don't completely understand the issue, I think. Also, I'm not actively developing this extension at the moment, so if someone does fix this another way please submit a pull request!

I am closing this for now.

**Comment by ukguy** [comment]
I feel we need to add a comment to this old forum to stop people using this

****IMPORTANT*****
Do not use the solution above, I found out it's wrong. I tested with fake domains and it made no difference. Yes it gets java working but it uses x-requested-with which we are not supposed to use. Infact it's only that line which triggers the java. It is not protected with the domains.

Use this...

<IfModule mod_headers.c>
Header add Access-Control-Allow-Origin "https://*.domain.com" 
</IfModule>

It took me hours and hours to get this working.

A note to anyone else, if your CDN is loading from the /pub/static folder, you need to put this at the top of the htaccess file in the static folder, NOT in the top level htaccesss file which it says everywhere!!

Also wrap it in the mod header tags

Hope this helps someone, I got so stressed out with it!
