### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by barbazul** [splashlab/magento-2-cors-requests#7]
Would you mind tagging a stable version so we do not need to lower the minimum-stability parameter in composer in order to use this extension.

I have been using it for about a year now without any issues, so I would say it is pretty stable.

Also publishing in packagist would be awesome

**Comment by thaddeusmt** [comment]
I have tagged a release (100.0.2) and attempted to [publish to Packagist](https://packagist.org/packages/splashlab/magento-2-cors-requests).

I hope that works for you, I am new to publishing PHP extensions.

**Comment by barbazul** [comment]
Thank you!

Really appreciate this.
